name: historiX
description: A historical exploration app with a multilingual AI chatbot.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.6 # iOS-style icons
  
  # State Management (Optional, if needed later)
  provider: ^6.0.5
  
  # Networking & APIs (If you need to fetch data)
  http: ^1.3.0 
  
  # Image Picker (If user uploads photos)
  image_picker: ^1.0.7

  # AI Chatbot Integration (For NLP processing)
  


  # Database (For PostgreSQL Storage)
  postgres: ^3.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/static/Roboto-Regular.ttf
        - asset: assets/fonts/static/Roboto-Bold.ttf
          weight: 700
